// src/client/el/helpers.ts
var hasDocument = typeof document !== "undefined";
function capitalize(str) {
  return str.charAt(0).toUpperCase() + str.slice(1);
}
function bindDocMethod(target, method) {
  return target && method ? method.bind(target) : void 0;
}
function isStateLike(value) {
  return !!value && typeof value === "object" && "value" in value && "subscribe" in value;
}
function isVNodeLike(value) {
  return !!value && typeof value === "object" && "tagName" in value;
}
function flattenChildren(children) {
  const flatChildren = [];
  for (let i2 = 0, len = children.length; i2 < len; i2++) {
    const child = children[i2];
    if (child == null || child === false) continue;
    if (Array.isArray(child)) {
      for (let j = 0, childLen = child.length; j < childLen; j++) {
        const nestedChild = child[j];
        if (nestedChild != null && nestedChild !== false) {
          flatChildren.push(nestedChild);
        }
      }
    } else {
      flatChildren.push(child);
    }
  }
  return flatChildren;
}

// src/client/el/factory.ts
var createElementFactory = (tag) => {
  return function(props, ...rest) {
    if (!arguments.length) {
      return { tagName: tag, props: {}, children: [] };
    }
    const isChild = typeof props !== "object" || Array.isArray(props) || props === null || isStateLike(props) || isVNodeLike(props);
    const actualProps = isChild ? {} : props;
    const args = isChild ? [props, ...rest] : rest;
    if (!args.length) {
      return { tagName: tag, props: actualProps, children: [] };
    }
    return { tagName: tag, props: actualProps, children: flattenChildren(args) };
  };
};
var frag = function(...children) {
  return { tagName: "", props: {}, children: flattenChildren(children) };
};

// src/client/el/tags.ts
var tags = [
  "html",
  "head",
  "body",
  "title",
  "base",
  "link",
  "meta",
  "style",
  "address",
  "article",
  "aside",
  "footer",
  "header",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "main",
  "nav",
  "section",
  "blockquote",
  "dd",
  "div",
  "dl",
  "dt",
  "figcaption",
  "figure",
  "hr",
  "li",
  "ol",
  "p",
  "pre",
  "ul",
  "a",
  "abbr",
  "b",
  "bdi",
  "bdo",
  "br",
  "cite",
  "code",
  "data",
  "dfn",
  "em",
  "i",
  "kbd",
  "mark",
  "q",
  "rp",
  "rt",
  "ruby",
  "s",
  "samp",
  "small",
  "span",
  "strong",
  "sub",
  "sup",
  "time",
  "u",
  "wbr",
  "area",
  "audio",
  "img",
  "map",
  "track",
  "video",
  "embed",
  "iframe",
  "object",
  "param",
  "picture",
  "portal",
  "source",
  "canvas",
  "noscript",
  "script",
  "del",
  "ins",
  "caption",
  "col",
  "colgroup",
  "table",
  "tbody",
  "td",
  "tfoot",
  "th",
  "thead",
  "tr",
  "button",
  "datalist",
  "fieldset",
  "form",
  "input",
  "label",
  "legend",
  "meter",
  "optgroup",
  "option",
  "output",
  "progress",
  "select",
  "textarea",
  "details",
  "dialog",
  "menu",
  "summary",
  "slot",
  "template"
];
var svgTags = [
  "svg",
  "circle",
  "rect",
  "path",
  "line",
  "polyline",
  "polygon",
  "ellipse",
  "g",
  "text",
  "tspan",
  "defs",
  "linearGradient",
  "radialGradient",
  "stop",
  "pattern",
  "mask",
  "clipPath",
  "use",
  "symbol",
  "marker",
  "image",
  "foreignObject",
  "animate",
  "animateTransform",
  "animateMotion",
  "set",
  "filter",
  "feBlend",
  "feColorMatrix",
  "feComponentTransfer",
  "feComposite",
  "feConvolveMatrix",
  "feDiffuseLighting",
  "feDisplacementMap",
  "feFlood",
  "feGaussianBlur",
  "feMorphology",
  "feOffset",
  "feSpecularLighting",
  "feTile",
  "feTurbulence"
];
var mathTags = [
  "math",
  "mi",
  "mn",
  "mo",
  "ms",
  "mtext",
  "mrow",
  "mfrac",
  "msqrt",
  "mroot",
  "msub",
  "msup"
];

// src/client/el/registry.ts
function createPrefixedFactories(tagsToCreate, prefix, elements2) {
  tagsToCreate.forEach((tag) => {
    const name = prefix + capitalize(tag);
    elements2[name] = createElementFactory(tag);
  });
}
var elements = {};
tags.forEach((tag) => {
  elements[tag] = createElementFactory(tag);
});
createPrefixedFactories(svgTags, "svg", elements);
createPrefixedFactories(mathTags, "math", elements);
elements.varElement = createElementFactory("var");
var {
  html,
  head,
  body,
  title,
  base,
  link,
  meta,
  style,
  address,
  article,
  aside,
  footer,
  header,
  h1,
  h2,
  h3,
  h4,
  h5,
  h6,
  main,
  nav,
  section,
  blockquote,
  dd,
  div,
  dl,
  dt,
  figcaption,
  figure,
  hr,
  li,
  ol,
  p,
  pre,
  ul,
  a,
  abbr,
  b,
  bdi,
  bdo,
  br,
  cite,
  code,
  data,
  dfn,
  em,
  i,
  kbd,
  mark,
  q,
  rp,
  rt,
  ruby,
  s,
  samp,
  small,
  span,
  strong,
  sub,
  sup,
  time,
  u,
  wbr,
  area,
  audio,
  img,
  map,
  track,
  video,
  embed,
  iframe,
  object,
  param,
  picture,
  portal,
  source,
  canvas,
  noscript,
  script,
  del,
  ins,
  caption,
  col,
  colgroup,
  table,
  tbody,
  td,
  tfoot,
  th,
  thead,
  tr,
  button,
  datalist,
  fieldset,
  form,
  input,
  label,
  legend,
  meter,
  optgroup,
  option,
  output,
  progress,
  select,
  textarea,
  details,
  dialog,
  menu,
  summary,
  slot,
  template,
  svgSvg,
  svgCircle,
  svgRect,
  svgPath,
  svgLine,
  svgPolyline,
  svgPolygon,
  svgEllipse,
  svgG,
  svgText,
  svgTspan,
  svgDefs,
  svgLinearGradient,
  svgRadialGradient,
  svgStop,
  svgPattern,
  svgMask,
  svgClipPath,
  svgUse,
  svgSymbol,
  svgMarker,
  svgImage,
  svgForeignObject,
  svgAnimate,
  svgAnimateTransform,
  svgAnimateMotion,
  svgSet,
  svgFilter,
  svgFeBlend,
  svgFeColorMatrix,
  svgFeComponentTransfer,
  svgFeComposite,
  svgFeConvolveMatrix,
  svgFeDiffuseLighting,
  svgFeDisplacementMap,
  svgFeFlood,
  svgFeGaussianBlur,
  svgFeMorphology,
  svgFeOffset,
  svgFeSpecularLighting,
  svgFeTile,
  svgFeTurbulence,
  mathMath,
  mathMi,
  mathMn,
  mathMo,
  mathMs,
  mathMtext,
  mathMrow,
  mathMfrac,
  mathMsqrt,
  mathMroot,
  mathMsub,
  mathMsup,
  varElement
} = elements;
var el = elements;

// src/client/el/dom-utils.ts
var doc = hasDocument ? document : void 0;
var getEl = bindDocMethod(doc, doc?.querySelector);
var getEls = bindDocMethod(doc, doc?.querySelectorAll);
var createEl = bindDocMethod(doc, doc?.createElement);
var createSvgEl = hasDocument ? doc.createElementNS.bind(doc, "http://www.w3.org/2000/svg") : void 0;
var createMathEl = hasDocument ? doc.createElementNS.bind(doc, "http://www.w3.org/1998/Math/MathML") : void 0;
var fragment = bindDocMethod(doc, doc?.createDocumentFragment);
var textNode = bindDocMethod(doc, doc?.createTextNode);
var commentNode = bindDocMethod(doc, doc?.createComment);
var getElId = bindDocMethod(doc, doc?.getElementById);
var getElClass = bindDocMethod(doc, doc?.getElementsByClassName);
var getElTag = bindDocMethod(doc, doc?.getElementsByTagName);
var getElName = bindDocMethod(doc, doc?.getElementsByName);
export {
  a,
  abbr,
  address,
  area,
  article,
  aside,
  audio,
  b,
  base,
  bdi,
  bdo,
  blockquote,
  body,
  br,
  button,
  canvas,
  caption,
  cite,
  code,
  col,
  colgroup,
  commentNode,
  createEl,
  createElementFactory,
  createMathEl,
  createSvgEl,
  data,
  datalist,
  dd,
  del,
  details,
  dfn,
  dialog,
  div,
  dl,
  doc,
  dt,
  el,
  elements,
  em,
  embed,
  fieldset,
  figcaption,
  figure,
  footer,
  form,
  frag,
  fragment,
  getEl,
  getElClass,
  getElId,
  getElName,
  getElTag,
  getEls,
  h1,
  h2,
  h3,
  h4,
  h5,
  h6,
  head,
  header,
  hr,
  html,
  i,
  iframe,
  img,
  input,
  ins,
  kbd,
  label,
  legend,
  li,
  link,
  main,
  map,
  mark,
  mathMath,
  mathMfrac,
  mathMi,
  mathMn,
  mathMo,
  mathMroot,
  mathMrow,
  mathMs,
  mathMsqrt,
  mathMsub,
  mathMsup,
  mathMtext,
  menu,
  meta,
  meter,
  nav,
  noscript,
  object,
  ol,
  optgroup,
  option,
  output,
  p,
  param,
  picture,
  portal,
  pre,
  progress,
  q,
  rp,
  rt,
  ruby,
  s,
  samp,
  script,
  section,
  select,
  slot,
  small,
  source,
  span,
  strong,
  style,
  sub,
  summary,
  sup,
  svgAnimate,
  svgAnimateMotion,
  svgAnimateTransform,
  svgCircle,
  svgClipPath,
  svgDefs,
  svgEllipse,
  svgFeBlend,
  svgFeColorMatrix,
  svgFeComponentTransfer,
  svgFeComposite,
  svgFeConvolveMatrix,
  svgFeDiffuseLighting,
  svgFeDisplacementMap,
  svgFeFlood,
  svgFeGaussianBlur,
  svgFeMorphology,
  svgFeOffset,
  svgFeSpecularLighting,
  svgFeTile,
  svgFeTurbulence,
  svgFilter,
  svgForeignObject,
  svgG,
  svgImage,
  svgLine,
  svgLinearGradient,
  svgMarker,
  svgMask,
  svgPath,
  svgPattern,
  svgPolygon,
  svgPolyline,
  svgRadialGradient,
  svgRect,
  svgSet,
  svgStop,
  svgSvg,
  svgSymbol,
  svgText,
  svgTspan,
  svgUse,
  table,
  tbody,
  td,
  template,
  textNode,
  textarea,
  tfoot,
  th,
  thead,
  time,
  title,
  tr,
  track,
  u,
  ul,
  varElement,
  video,
  wbr
};
